steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build',
         '-t',
         'gcr.io/my-project/my-image',
         '.',
         '-f',
         'continuous_integration/36_pytest.dockerfile']
  waitFor: ['-']
  timeout: 1200s
- name: 'gcr.io/cloud-builders/docker'
  args: ['build',
         '-t',
         'gcr.io/my-project/my-image',
         '.',
         '-f',
         'continuous_integration/37_pytest.dockerfile']
  waitFor: ['-']
  timeout: 1200s
- name: 'gcr.io/cloud-builders/docker'
  args: ['build',
         '-t',
         'gcr.io/my-project/my-image',
         '.',
         '-f',
         'continuous_integration/38_pytest.dockerfile']
  waitFor: ['-']
  timeout: 1200s
- name: 'gcr.io/cloud-builders/docker'
  args: ['build',
         '-t',
         'gcr.io/my-project/my-image',
         '.',
         '-f',
         'continuous_integration/39_pytest_ci.dockerfile']
  waitFor: ['-']
  timeout: 1200s